version: "3.8"
services:
  postgresDB:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=user_netflix
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_mininetflix
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5436:5432"